// ============================================================================
// MUSIC GENRE TAXONOMY -- PRODUCTION SOURCE OF TRUTH (Step 3-1).
// ============================================================================
//
// Controlled genre taxonomy for the genre-first catalog reclassification
// (Step 3-1). Moved verbatim from docs/music-genre-taxonomy.ts (accepted
// migration input) once genre classification data equality was proven
// against docs/music-catalog-genre-classification-revised-draft.ts.
//
// Built by inspecting the 673-track catalog's existing lane assignments,
// legacy broad `genre` field, and per-track subTags/moodTags, then grounded
// with real artist/genre knowledge -- not derived from numeric sound/
// atmosphere stats.
//
// This taxonomy is intentionally practical, not academically exhaustive:
// broad labels (pop, rock, electronic, indie, alternative) are never used
// alone without a useful subgenre, and one/two-track "microscopic" labels
// were avoided unless musically necessary.
// ============================================================================

export type PrimaryGenre =
  | "pop"
  | "hip-hop"
  | "rnb-soul"
  | "rock"
  | "jazz"
  | "electronic"
  | "folk-acoustic"
  | "funk-disco"
  | "ambient-experimental";

export const PRIMARY_GENRES: Array<{ id: PrimaryGenre; label: string; description: string }> = [
  { id: "pop", label: "Pop", description: "Mainstream and adjacent song-oriented pop music not better described by a more specific family." },
  { id: "hip-hop", label: "Hip-Hop", description: "Rap-led and beat-led hip-hop, including lofi/instrumental hip-hop." },
  { id: "rnb-soul", label: "R&B / Soul", description: "Contemporary and classic rhythm & blues and soul, including neo-soul and K-R&B." },
  { id: "rock", label: "Rock", description: "Guitar/band-based rock lineage, including alt-rock, indie-rock, dream-pop and shoegaze." },
  { id: "jazz", label: "Jazz", description: "Jazz and jazz-fusion, including modern jazz-hop and lounge/acid jazz." },
  { id: "electronic", label: "Electronic", description: "Dance-floor and production-led electronic music (house, synthwave, future bass)." },
  { id: "folk-acoustic", label: "Folk / Acoustic", description: "Acoustic-guitar-led singer-songwriter, indie-folk and Americana." },
  { id: "funk-disco", label: "Funk / Disco", description: "Groove-first funk and disco, classic and revival." },
  { id: "ambient-experimental", label: "Ambient / Experimental", description: "Instrumental, largely beatless or texture-first ambient and downtempo electronic music." },
];

export type Subgenre =
  | "dance-pop"
  | "synth-pop"
  | "electropop"
  | "bedroom-pop"
  | "indie-pop"
  | "k-pop"
  | "j-pop"
  | "city-pop"
  | "teen-pop"
  | "soft-pop"
  | "art-pop"
  | "mainstream-rap"
  | "trap"
  | "melodic-rap"
  | "lofi-hiphop"
  | "jazz-rap"
  | "alternative-hip-hop"
  | "boom-bap"
  | "drill"
  | "east-coast-hip-hop"
  | "west-coast-hip-hop"
  | "k-hiphop"
  | "cloud-rap"
  | "contemporary-rnb"
  | "neo-soul"
  | "classic-soul"
  | "motown-soul"
  | "alt-rnb"
  | "k-rnb"
  | "alternative-rock"
  | "indie-rock"
  | "dream-pop"
  | "shoegaze"
  | "j-rock"
  | "k-indie-rock"
  | "britpop"
  | "garage-rock"
  | "power-pop"
  | "pop-punk"
  | "modern-jazz"
  | "acid-jazz"
  | "nu-jazz"
  | "jazz-hop"
  | "bossa-nova"
  | "lounge-jazz"
  | "house"
  | "deep-house"
  | "progressive-house"
  | "tropical-house"
  | "synthwave"
  | "future-bass"
  | "indie-folk"
  | "singer-songwriter"
  | "americana"
  | "folk-pop"
  | "cinematic-folk"
  | "disco-funk"
  | "classic-funk"
  | "disco"
  | "nu-disco"
  | "boogie"
  | "ambient-electronic"
  | "downtempo"
  | "cinematic-ambient"
  | "lofi-ambient";

// Canonical subgenres grouped under each primary genre.
export const SUBGENRES_BY_PRIMARY: Record<PrimaryGenre, Subgenre[]> = {
  "pop": ["dance-pop", "synth-pop", "electropop", "bedroom-pop", "indie-pop", "k-pop", "j-pop", "city-pop", "teen-pop", "soft-pop", "art-pop"],
  "hip-hop": ["mainstream-rap", "trap", "melodic-rap", "lofi-hiphop", "jazz-rap", "alternative-hip-hop", "boom-bap", "drill", "east-coast-hip-hop", "west-coast-hip-hop", "k-hiphop", "cloud-rap"],
  "rnb-soul": ["contemporary-rnb", "neo-soul", "classic-soul", "motown-soul", "alt-rnb", "k-rnb"],
  "rock": ["alternative-rock", "indie-rock", "dream-pop", "shoegaze", "j-rock", "k-indie-rock", "britpop", "garage-rock", "power-pop", "pop-punk"],
  "jazz": ["modern-jazz", "acid-jazz", "nu-jazz", "jazz-hop", "bossa-nova", "lounge-jazz"],
  "electronic": ["house", "deep-house", "progressive-house", "tropical-house", "synthwave", "future-bass"],
  "folk-acoustic": ["indie-folk", "singer-songwriter", "americana", "folk-pop", "cinematic-folk"],
  "funk-disco": ["disco-funk", "classic-funk", "disco", "nu-disco", "boogie"],
  "ambient-experimental": ["ambient-electronic", "downtempo", "cinematic-ambient", "lofi-ambient"],
};

// Editorial notes on non-obvious subgenre placement decisions.
export const SUBGENRE_NOTES: Partial<Record<Subgenre, string>> = {
  "dream-pop": "Filed under rock, not pop: catalog's dream-pop/shoegaze acts (Slowdive, Beach House, Cigarettes After Sex, The Japanese House, M83) are guitar/band-based and share direct lineage with alt-rock and shoegaze, despite the 'pop' in the name.",
  "jazz-hop": "Filed under jazz, not hip-hop: instrumental/lightly-rapped jazz-sample beat music (Nujabes-lineage) where the jazz identity is dominant; use hip-hop primary + jazz-rap when the rap/verse identity is dominant instead.",
  "ambient-electronic": "Reserved for largely beatless, texture-first instrumental electronic (e.g. Tycho) — distinct from lofi-hiphop, which retains a hip-hop drum/beat backbone.",
  "city-pop": "Covers Japanese and Korean retro-glow, funk-tinged pop (city-pop, k-city-pop, japanese-city-pop, retro-pop-with-funk-bassline).",
};

// Which OTHER primary genres a track's crossoverGenres may reach into,
// given its primaryGenre. Same-primary subgenre crossovers (e.g. a
// dream-pop track crossing over into shoegaze) are always allowed and are
// not enumerated here.
//
// Known gap (accepted as-is, not resolved in this migration): 6 tracks in
// the accepted Step 3-1 classification use a crossover subgenre whose
// primary genre is not listed here for their own primaryGenre (rock ->
// rnb-soul via "alt-rnb" for 2 The xx tracks; hip-hop -> ambient-experimental
// via "ambient-electronic" for 4 lofi-hiphop tracks). Both are well-reasoned
// artist-knowledge classifications. The production validator reports these
// as informational warnings, not failures — this table is a verbatim move
// of the accepted docs/music-genre-taxonomy.ts content, not independently
// edited.
export const CROSSOVER_ADJACENCY: Record<PrimaryGenre, PrimaryGenre[]> = {
  "pop": ["rnb-soul", "electronic", "rock", "funk-disco", "hip-hop", "folk-acoustic", "jazz"],
  "hip-hop": ["rnb-soul", "jazz", "pop", "electronic"],
  "rnb-soul": ["hip-hop", "jazz", "funk-disco", "pop"],
  "rock": ["pop", "folk-acoustic", "ambient-experimental", "electronic"],
  "jazz": ["hip-hop", "rnb-soul", "funk-disco", "pop"],
  "electronic": ["pop", "ambient-experimental", "funk-disco", "rock", "hip-hop"],
  "folk-acoustic": ["pop", "rock", "ambient-experimental"],
  "funk-disco": ["rnb-soul", "jazz", "pop", "electronic"],
  "ambient-experimental": ["electronic", "rock", "folk-acoustic"],
};

// Normalization map from raw legacy tags (subTags/moodTags found in the
// source catalog) to a canonical Subgenre id, or `null` when the tag is a
// mood/scene descriptor rather than a genre signal (e.g. "midnight",
// "romantic", "road-trip") and must never be used as a genre or crossover
// value. Used only as supporting evidence during classification, never as
// the sole basis for a decision.
export const TAG_ALIASES: Record<string, Subgenre | null> = {
  "alt-pop": null,
  "soft-pop": "soft-pop",
  "electro-pop": "electropop",
  "electronic-pop": "electropop",
  "edm-pop": "electropop",
  "modern-jrock": "j-rock",
  "classic-jrock": "j-rock",
  "stylish-jrock": "j-rock",
  "post-britpop": "britpop",
  "k-indie": "k-indie-rock",
  "k-indie-pop": "indie-pop",
  "lofi-rnb": "alt-rnb",
  "soft-rnb": "alt-rnb",
  "mellow-rnb": "alt-rnb",
  "dark-rnb": "alt-rnb",
  "groove-rnb": "alt-rnb",
  "minimal-rnb": "alt-rnb",
  "smooth-rnb": "alt-rnb",
  "trap-rnb": "alt-rnb",
  "motown": "motown-soul",
  "vocal-soul": "classic-soul",
  "southern-soul": "classic-soul",
  "blues-soul": "classic-soul",
  "smooth-soul": "classic-soul",
  "soul-pop": "classic-soul",
  "acoustic-soul": "neo-soul",
  "japanese-city-pop": "city-pop",
  "modern-city-pop": "city-pop",
  "k-city-pop": "city-pop",
  "city-pop-adjacent": "city-pop",
  "classic-city-pop": "city-pop",
  "dark-city-pop": "city-pop",
  "japanese-jazz-hop": "jazz-hop",
  "beat-jazz": "jazz-hop",
  "trap-jazz": "jazz-rap",
  "neo-soul-jazz": "neo-soul",
  "east-coast-hip-hop": "east-coast-hip-hop",
  "west-coast-rap": "west-coast-hip-hop",
  "west-coast-hip-hop": "west-coast-hip-hop",
  "atlanta-rap": "trap",
  "trap-lite": "trap",
  "southern-rap": "trap",
  "uk-drill": "drill",
  "brooklyn-drill": "drill",
  "conscious-rap": "alternative-hip-hop",
  "gospel-rap": "alternative-hip-hop",
  "grime": "alternative-hip-hop",
  "uk-rap": "alternative-hip-hop",
  "rage-rap": "cloud-rap",
  "chillhop": "lofi-hiphop",
  "instrumental-hiphop": "lofi-hiphop",
  "lofi-beats": "lofi-hiphop",
  "jazzy-hiphop": "jazz-rap",
  "jazzy-beats": "lofi-hiphop",
  "shoegaze-rock": "shoegaze",
  "shoegaze-adjacent": "shoegaze",
  "modern-shoegaze": "shoegaze",
  "classic-shoegaze": "shoegaze",
  "dream-pop-adjacent": "dream-pop",
  "college-rock": "indie-rock",
  "arena-rock": "alternative-rock",
  "blues-rock": "alternative-rock",
  "post-punk": "alternative-rock",
  "post-punk-revival": "alternative-rock",
  "post-grunge": "alternative-rock",
  "grunge": "alternative-rock",
  "psychedelic-rock": "alternative-rock",
  "slacker-rock": "alternative-rock",
  "art-rock": "alternative-rock",
  "desert-rock": "alternative-rock",
  "stadium-rock": "alternative-rock",
  "stadium-alternative": "alternative-rock",
  "southern-alt-rock": "alternative-rock",
  "alt-country": "americana",
  "heartland-indie": "indie-rock",
  "acoustic-indie": "indie-folk",
  "rainy-indie": "indie-rock",
  "sad-indie": "indie-rock",
  "dreamy-indie": "indie-rock",
  "retro-indie": "indie-rock",
  "autumn-indie": "indie-rock",
  "winter-indie": "indie-rock",
  "indie-classic": "indie-rock",
  "indie-electronic": "ambient-electronic",
  "sophisti-pop": "city-pop",
  "baroque-pop": "indie-pop",
  "psych-pop": "indie-pop",
  "minimal-pop": "bedroom-pop",
  "ethereal-pop": "dream-pop",
  "cosmic-pop": "dream-pop",
  "hazy-pop": "dream-pop",
  "dreamy-pop": "dream-pop",
  "sad-pop": "bedroom-pop",
  "internet-pop": "bedroom-pop",
  "bright-pop": "teen-pop",
  "girly-pop": "teen-pop",
  "highteen-pop-rock": "teen-pop",
  "teen-pop-rock": "teen-pop",
  "cute-pop": "teen-pop",
  "queer-pop": "teen-pop",
  "quirky-pop": "indie-pop",
  "guitar-pop": "power-pop",
  "surf-pop": "power-pop",
  "sunny-rock": "power-pop",
  "island-pop": "folk-pop",
  "beach-folk": "folk-pop",
  "folk-pop": "folk-pop",
  "acoustic-pop": "folk-pop",
  "piano-pop": "soft-pop",
  "piano-rock": "singer-songwriter",
  "piano-soul": "classic-soul",
  "piano-beats": "lofi-hiphop",
  "cinematic-folk": "cinematic-folk",
  "sunshine-pop": "soft-pop",
  "retro-pop": "city-pop",
  "80s-pop": "synth-pop",
  "retro-synth": "synth-pop",
  "synth-dream": "dream-pop",
  "synth-lofi": "lofi-ambient",
  "lofi-synth": "lofi-ambient",
  "ambient-lofi": "lofi-ambient",
  "ambient-rock": "shoegaze",
  "ambient-pop": "dream-pop",
  "ambient-folk": "cinematic-folk",
  "cinematic-electronic": "cinematic-ambient",
  "cinematic-rap": "alternative-hip-hop",
  "cinematic-hiphop": "alternative-hip-hop",
  "dark-hiphop": "trap",
  "dark-pop-rap": "trap",
  "hard-rap": "trap",
  "battle-rap": "boom-bap",
  "menacing": null,
  "north-soul": null,
  "northern-soul": "classic-soul",
  "newjack-pop": "contemporary-rnb",
  "uk-garage-pop": "house",
  "garage-house": "house",
  "french-house": "house",
  "modern-edm": "future-bass",
  "future-bass": "future-bass",
  "synthwave": "synthwave",
  "retro-electronic": "synthwave",
  "retro-future": "synthwave",
  "dream-electronic": "ambient-electronic",
  "hyper-pop": null,
  "melodic-hardcore": null,
  "p-funk": "classic-funk",
  "funk-house": "nu-disco",
  "electro-disco": "nu-disco",
  "post-disco": "nu-disco",
  "modern-disco": "nu-disco",
  "modern-funk": "disco-funk",
  "city-funk": "disco-funk",
  "smooth-funk": "disco-funk",
  "bedroom-funk": "disco-funk",
  "party-funk": "disco-funk",
  "soft-funk": "disco-funk",
  "funk-jazz": "acid-jazz",
  "jazz-funk": "acid-jazz",
  "funk-soul": "neo-soul",
  "funk-rap": "jazz-rap",
  "funk-pop": "disco-funk",
  "bassline-pop": "disco-funk",
  "dance-classic": "disco",
  "dancefloor-classic": "disco",
  "dancefloor-pop": "dance-pop",
  "classic-groove": "disco",
  "80s-groove": "disco",
  "80s-night": "disco",
  "doo-wop": "classic-soul",
  "oldies": "classic-soul",
  "bright-oldies": "classic-soul",
  "motown-funk": "motown-soul",
  "rnb-pop": "contemporary-rnb",
  "rnb-dance": "contemporary-rnb",
  "pop-rnb": "contemporary-rnb",
  "rnb-rap": "alt-rnb",
  "rap-rnb": "alt-rnb",
  "hiphop-rnb": "alt-rnb",
  "soul-rnb": "neo-soul",
  "romantic-rnb": "contemporary-rnb",
  "dream-rnb": "alt-rnb",
  "rap-rock": "alternative-rock",
  "pop-rock": "alternative-rock",
  "pop-rock-rush": "alternative-rock",
  "indie-pop-rock": "indie-pop",
  "youth-pop-rock": "power-pop",
  "melodic-rock": "alternative-rock",
  "modern-rock": "alternative-rock",
  "classic-modern-rock": "alternative-rock",
  "classic-alternative": "alternative-rock",
  "modern-classic": "alternative-rock",
  "emo-rock": "alternative-rock",
  "emo-indie": "indie-rock",
  "americana-drive": "americana",
  "heartland-drive": "americana",
  "heartland-punk": "americana",
  "j-pop": "j-pop",
  "modern-jpop": "j-pop",
  "modern-jpop-rock": "j-rock",
  "anime-rock": "j-rock",
  "anime-electronic": "synthwave",
  "k-band": "k-indie-rock",
  "k-pop-ballad": "k-pop",
  "boy-group": "k-pop",
  "girl-group": "k-pop",
  "global-pop": "dance-pop",
  "afro-pop": "dance-pop",
  "tropical-pop": "tropical-house",
  "resort-pop": "tropical-house",
  "beach-pop": "dance-pop",
  "beach-anthem": "dance-pop",
  "party-pop": "dance-pop",
  "club-chic": "dance-pop",
  "fashion-pop": "dance-pop",
  "trend-pop": "dance-pop",
  "trendy-pop": "dance-pop",
  "attitude-pop": "dance-pop",
  "performance-pop": "dance-pop",
  "solo-pop": "dance-pop",
  "confidence-pop": "dance-pop",
  "cyber-chic": "electropop",
  "glow-pop": "electropop",
  "house-pop": "house",
  "tropical-house": "tropical-house",
  "progressive-house": "progressive-house",
  "deep-house": "deep-house",
  "festival-pop": "progressive-house",
  "acid-jazz": "acid-jazz",
  "nu-jazz": "nu-jazz",
  "uk-jazz": "nu-jazz",
  "smooth-jazz-pop": "acid-jazz",
  "smooth-jazz-soul": "acid-jazz",
  "modern-vocal-jazz": "lounge-jazz",
  "lounge-classic": "lounge-jazz",
  "easy-listening": "lounge-jazz",
  "jazz-vocal": "lounge-jazz",
  "jazz-soul": "neo-soul",
  "jazz-pop": "soft-pop",
  "mellow-jazz": "lounge-jazz",
  "modern-fusion": "acid-jazz",
  "guitar-groove": "acid-jazz",
  "broken-beat": "acid-jazz",
  "melodic-rap": "melodic-rap",
  "minimal-rap": "melodic-rap",
  "alt-rap": "alternative-hip-hop",
  "alternative-rap": "alternative-hip-hop",
  "psychedelic-rap": "cloud-rap",
  "cloud-rap": "cloud-rap",
  "swagger-rap": "mainstream-rap",
  "fashion-rap": "mainstream-rap",
  "confidence-rap": "mainstream-rap",
  "technical-rap": "mainstream-rap",
  "luxury-rap": "mainstream-rap",
  "classic-rap": "boom-bap",
  "mainstream-rap": "mainstream-rap",
  "mainstream-heavy": "trap",
  "modern-hiphop": "trap",
  "modern-rap": "trap",
  "dark-rap": "trap",
  "dark-swagger": "trap",
  "dark-street": "trap",
  "dark-energy": "trap",
  "dark-night": "trap",
  "night-heavy": "trap",
  "heavy-rap": "trap",
  "anthemic-rap": "trap",
  "industrial-rap": "trap",
  "metro-boomin": "trap",
  "street-rap": "trap",
  "street-flex": "trap",
  "street-bounce": "trap",
  "street-youth": "trap",
  "crew-track": "trap",
  "urban-swagger": "trap",
  "modern-swagger": "trap",
  "harlem-swagger": "east-coast-hip-hop",
  "big-city-flex": "mainstream-rap",
  "late-night-luxury": "mainstream-rap",
  "cruising-rap": "mainstream-rap",
  "chill-rap": "cloud-rap",
  "producer-rap": "trap",
  "neo-soul-hop": "jazz-rap",
  "k-hiphop": "k-hiphop",
  "japanese-road": "j-rock",
  "j-rock": "j-rock",
  "highway-rush": null,
  "sports-rush": null,
  "action-rush": null,
  "cinematic-rush": null,
  "restless-rush": null,
  "girl-band-rock": "k-indie-rock",
  "mixture-rock": "alternative-rock",
  "city-rock": "j-rock",
  "jazz-rock": "acid-jazz",
  "blue-sky-rock": "power-pop",
  "shortform-friendly": null,
  "study-beats": "lofi-hiphop",
  "study-loop": "lofi-hiphop",
  "study-focus": "lofi-ambient",
  "calm-focus": "lofi-ambient",
  "peaceful-study": "lofi-ambient",
  "cozy-study": "lofi-hiphop",
  "late-night-study": "lofi-hiphop",
  "soulful-lofi": "lofi-hiphop",
  "dusty-beats": "lofi-hiphop",
  "quiet-drift": "lofi-ambient",
  "quiet-focus": "lofi-ambient",
  "quiet-solitude": "lofi-ambient",
  "night-solitude": "lofi-ambient",
  "bedroom-night": "lofi-hiphop",
  "bedroom-calm": "ambient-electronic",
  "bedroom-solitude": "lofi-hiphop",
  "soft-focus": "ambient-electronic",
  "soft-morning": "ambient-electronic",
  "misty-morning": "ambient-electronic",
  "winter-beats": "lofi-hiphop",
  "sleepy-beats": "lofi-hiphop",
  "chill-beats": "lofi-hiphop",
  "calm-beats": "lofi-ambient",
  "instrumental": "ambient-electronic",
  "nostalgia-core": "bedroom-pop",
  "viral-sad": "bedroom-pop",
  "soft-loneliness": "bedroom-pop",
  "late-night-feelings": "alt-rnb",
  "late-night-text": "alt-rnb",
  "smooth-cruise": "contemporary-rnb",
  "loner-cruise": "alt-rnb",
  "dark-cruise": "alt-rnb",
  "psychedelic-soul": "neo-soul",
  "urban-ballad": "contemporary-rnb",
  "minimal-groove": "alt-rnb",
  "alt-pop-rnb": "alt-rnb",
  "rainy-rnb": "alt-rnb",
  "seoul-night": "k-rnb",
  "river-drive": null,
  "female-vocal": null,
  "duet": null,
  "duet-pop": "soft-pop",
  "diva-soul": "classic-soul",
  "empowered": null,
  "classic-pop-soul": "classic-soul",
  "classic-love": "classic-soul",
  "grand-romance": "classic-soul",
  "deep-love": "classic-soul",
  "dramatic-love": "classic-soul",
  "blue-eyed-soul": "classic-soul",
  "old-romance": "classic-soul",
  "old-film-energy": "classic-soul",
  "cinematic-classic": "classic-soul",
  "groove-soul": "neo-soul",
  "minimal-soul": "neo-soul",
  "morning-cafe": "soft-pop",
  "mellow-duet": "soft-pop",
  "romantic-cafe": "soft-pop",
  "soft-acoustic": "folk-pop",
  "brunch-cafe": "soft-pop",
  "soft-lounge": "lounge-jazz",
  "cozy-romance": "soft-pop",
  "90s-pop": "soft-pop",
  "blues-pop": "soft-pop",
  "mellow-cafe": "soft-pop",
  "cafe-soul": "neo-soul",
  "old-cafe": "soft-pop",
  "cafe-pop": "soft-pop",
  "cafe-romance": "soft-pop",
  "warm-cafe": null,
  "classic-cafe": "soft-pop",
  "sax-groove": "acid-jazz",
  "sax-pop": "acid-jazz",
  "trap-pop": "trap",
  "sunny-pop": "dance-pop",
  "sunshine-drive": null,
  "bubbly-pop": "teen-pop",
  "soft-sunshine": "soft-pop",
  "daylight-groove": "disco-funk",
  "playful-groove": "disco-funk",
  "groove-pop": "dance-pop",
  "brass-pop": "disco-funk",
  "story-pop": "soft-pop",
  "bright-pop-rock": "power-pop",
  "k-pop-ballad-x": null,
  "warm-pop": "soft-pop",
  "jazzy-pop": "soft-pop",
  "elegant-disco": "disco",
  "boogie-night": "disco",
  "feel-good-disco": "disco",
  "freedom-anthem": "disco",
  "night-strut": "disco",
  "night-funk": "disco-funk",
  "sleek-groove": "disco-funk",
  "cosmic-groove": "disco-funk",
  "luxury-groove": "disco-funk",
  "elegant-groove": "disco-funk",
  "elegant-night": "disco",
  "chic-groove": "disco-funk",
  "chic-pop": "disco-funk",
  "smooth-chic": "disco-funk",
  "soft-chic": "disco-funk",
  "fresh-chic": "dance-pop",
  "fresh-pop": "dance-pop",
  "modern-chic": "dance-pop",
  "urban-groove": "disco-funk",
  "urban-cool": "contemporary-rnb",
  "urban-drive": "contemporary-rnb",
  "urban-night": "contemporary-rnb",
  "urban-pop": "contemporary-rnb",
  "urban-rnb": "contemporary-rnb",
  "urban-rock": "alternative-rock",
  "urban-rush": null,
  "urban-style": "contemporary-rnb",
  "urban-grit": "alt-rnb",
  "urban-glow": "contemporary-rnb",
  "urban": null,
  "night-groove": "disco-funk",
  "night-pop": "electropop",
  "night-drive": null,
  "night-cruise": null,
  "night-rush": null,
  "night-ride": null,
  "night-energy": null,
  "night-emotion": null,
  "night-radio": null,
  "night-romance": null,
  "night-haze": null,
  "night-reflection": null,
  "smooth-night": "contemporary-rnb",
  "romantic-groove": "neo-soul",
  "romantic-night": null,
  "midnight": null,
  "midnight-groove": "disco-funk",
  "midnight-drive": null,
  "midnight-room": null,
  "glossy-night": "electropop",
  "bright-neon": "synthwave",
  "dark-neon": "synthwave",
  "neon-drive": null,
  "neon-night": "synthwave",
  "neon-ride": null,
  "neon-energy": "synthwave",
  "club-night": "house",
  "club-classic": "disco",
  "dance-night": "dance-pop",
  "festival-night": "progressive-house",
  "festival-summer": "tropical-house",
  "global-summer": "tropical-house",
  "summer-groove": "disco-funk",
  "summer-night": null,
  "summer-drive": null,
  "vacation-pop": "tropical-house",
  "ocean-pop": "folk-pop",
  "ocean-drive": null,
  "west-coast-pop": "power-pop",
  "west-coast-haze": "dream-pop",
  "surf-rock": "power-pop",
  "ska-pop": "power-pop",
  "beach-rock": "power-pop",
  "beach-drive": null,
  "sunny-groove": "disco-funk",
  "sunny-energy": null,
  "sunny-drive": null,
  "sunshine-pop-x": null,
  "soft-beach": "folk-pop",
  "soft-summer": "folk-pop",
  "heat-haze": "dream-pop",
  "coastal": null,
  "coastal-drive": null,
  "travel-pop": "folk-pop",
  "travel-folk": "indie-folk",
  "travel-romance": null,
  "travel-memory": null,
  "wander": null,
  "wide-drive": null,
  "wide-haze": "dream-pop",
  "wide-landscape": null,
  "wide-road": null,
  "warm-road": null,
  "warm-memory": null,
  "warm-groove": "neo-soul",
  "pastoral": "cinematic-folk",
  "wilderness": "cinematic-folk",
  "quiet-road": "singer-songwriter",
  "uplift": null,
  "uplifting-drive": null,
  "uplifting": null,
  "sunset-folk": "folk-pop",
  "group-vocal": null,
  "farewell-road": null,
  "road-pop": "folk-pop",
  "storytelling": null,
  "road-movie": null,
  "road-story": null,
  "road-release": null,
  "road-riff": "americana",
  "road-anthem": "americana",
  "road-rock": "americana",
  "road-rush": "americana",
  "road-memory": null,
  "road-trip": null,
  "open-road": null,
  "open-air": null,
  "open-drive": null,
  "highway-rock": "americana",
  "drive": null,
  "drive-scene": null,
  "drive-anthem": "americana",
  "driving-piano": "singer-songwriter",
  "driving-groove": "disco-funk",
  "emotional-drive": null,
  "emotional-road": null,
  "moody-drive": "dream-pop",
  "lonely-drive": "singer-songwriter",
  "melancholy-drive": "indie-rock",
  "cinematic-road": "cinematic-folk",
  "cinematic-rock": "alternative-rock",
  "cinematic-fog": "dream-pop",
  "cinematic-haze": "dream-pop",
  "cinematic-night": "dream-pop",
  "cinematic": null,
  "cinematic-pop": "soft-pop",
  "sports-rush-x": null,
  "sad-indie-x": null,
  "teenage-drive": "power-pop",
  "suburban-drive": "power-pop",
  "freedom-drive": "power-pop",
  "youth-rush": "power-pop",
  "youth-drive": "power-pop",
  "youth-anthem": "power-pop",
  "youth-rock": "power-pop",
  "youth-pop": "teen-pop",
  "youth-escape": "power-pop",
  "youth-release": "power-pop",
  "youth-nostalgia": "indie-rock",
  "youth": null,
  "harmony-rock": "power-pop",
  "nature-drive": "americana",
  "heavy-drive": "alternative-rock",
  "heavy-dream": "shoegaze",
  "heavy-energy": "trap",
  "heavy-bass": "trap",
  "bass-heavy": "trap",
  "bass-groove": "disco-funk",
  "dark-groove": "alt-rnb",
  "retro-groove": "disco",
  "retro-drive": "synth-pop",
  "retro-night": "synth-pop",
  "retro-haze": "dream-pop",
  "retro-romance": "city-pop",
  "retro-summer": "city-pop",
  "modern-groove": "acid-jazz",
  "modern-pop": "dance-pop",
  "modern-retro": "city-pop",
  "modern-romance": null,
  "bright-night": "synthwave",
  "big-city-flex-x": null,
  "americana": "americana",
  "punk-rock": "garage-rock",
  "garage-rock": "garage-rock",
  "girl-group-x": null,
  "k-pop": "k-pop",
  "k-rnb": "k-rnb",
  "k-hiphop-x": "k-hiphop",
  "k-indie-rock": "k-indie-rock",
  "k-city-pop-x": "city-pop",
  "quiet-room": "lofi-ambient",
  "cozy-room": "lofi-ambient",
  "cozy": null,
  "distance": null,
  "young-love": null,
  "young-romance": null,
  "summer-love": null,
  "heartbreak-pop": "soft-pop",
  "breakup-pop": "soft-pop",
  "breakup-anthem": "dance-pop",
  "breakup": null,
  "revenge-pop": "dance-pop",
  "flirty-pop": "dance-pop",
  "playful-breakup": "dance-pop",
  "playful-pop": "dance-pop",
  "teen-crush": "teen-pop",
  "crush-anthem": "teen-pop",
  "highschool-crush": "teen-pop",
  "highschool-drama": "teen-pop",
  "highschool-feelings": "teen-pop",
  "relationship-drama": "teen-pop",
  "party-drama": "dance-pop",
  "soft-highteen": "teen-pop",
  "stylish-teen": "teen-pop",
  "teen-angst": "teen-pop",
  "teen-romance": "teen-pop",
  "teenage-room": "bedroom-pop",
  "modern-highteen": "teen-pop",
  "highteen-party": "teen-pop",
  "highteen-rebel": "teen-pop",
  "highteen-romance": "teen-pop",
  "2000s-highteen": "teen-pop",
  "young-pop": "teen-pop",
  "friend-group": null,
  "country-pop": "americana",
  "timeless-love": null,
  "romance": null,
  "romantic": null,
  "romance-pop": "soft-pop",
  "classic-romance": "classic-soul",
  "wedding-romance": "classic-soul",
  "soft-romance": "soft-pop",
  "old-romance-x": null,
  "heartfelt": null,
  "reflective": null,
  "sentimental": null,
  "nostalgia": null,
  "nostalgic": null,
  "melancholic": null,
  "melancholy": null,
  "moody": null,
  "moody-room": "bedroom-pop",
  "dramatic": null,
  "intimate": null,
  "memory": null,
  "soft-memory": null,
  "soft-night": null,
  "soft-haze": "dream-pop",
  "soft-drive": "dream-pop",
  "soft-guitar": "singer-songwriter",
  "soft-vocal": null,
  "soft-ballad": "soft-pop",
  "soft-retro": "city-pop",
  "soft-synth": "synth-pop",
  "everyday-melancholy": null,
  "deep-melancholy": null,
  "deep-vocal": null,
  "deep-night": null,
  "blue-night": null,
  "blue-haze": "dream-pop",
  "blue-sky-rock-x": null,
  "rainy-night": null,
  "rainy-mood": null,
  "rainy-pop": "bedroom-pop",
  "rainy-road": "indie-rock",
  "home": null,
  "bedroom": null,
  "teen-melancholy": "teen-pop",
  "classic-korean-pop": "k-pop",
  "boy-group-x": "k-pop",
  "girl-group-x2": "k-pop",
  "swagger": "mainstream-rap",
  "swagger-groove": "mainstream-rap",
  "swagger-drive": "mainstream-rap",
  "city-anthem": "mainstream-rap",
  "city-party": "trap",
  "city-drive": null,
  "night-rap": "trap",
  "cool-rap": "mainstream-rap",
  "rap": "mainstream-rap",
  "hazy-night": "dream-pop",
  "hazy-vocal": "shoegaze",
  "hazy-pop-x": "dream-pop",
  "desert-dream": "dream-pop",
  "surreal-drive": "dream-pop",
  "dream-drive": "dream-pop",
  "slow-dream": "dream-pop",
  "slow-rock": "alternative-rock",
  "slowcore": "shoegaze",
  "fuzzy-dream": "shoegaze",
  "dark-glam": "synth-pop",
  "dark-pop": "synth-pop",
  "glowing-pop": "dream-pop",
  "emotional-electronic": "cinematic-ambient",
  "emotional-pop": "soft-pop",
  "emotional-rock": "alternative-rock",
  "emotional-release": "alternative-rock",
  "emo-x": "alternative-rock",
  "atmospheric": "cinematic-ambient",
  "progressive": "progressive-house",
  "minimal": "ambient-electronic",
  "minimal-beat": "lofi-hiphop",
  "vocal-groove": "neo-soul",
  "positive-groove": "disco-funk",
  "feel-good": null,
  "feel-good-groove": "disco-funk",
  "feel-good-pop": "dance-pop",
  "classic-urban": "classic-soul",
  "coming-of-age": null,
  "golden-hour": null,
  "spring-pop": "soft-pop",
  "color-pop": "dance-pop",
  "daylight-pop": "soft-pop",
  "daylight": null,
  "bright-highteen": "teen-pop",
  "soulful-x": "neo-soul",
};

// Deprecated / disallowed labels: too vague to serve as a primaryGenre or
// subgenre on their own (per Step 3-1 instructions). If seen, resolve to a
// more specific canonical subgenre instead.
export const DEPRECATED_LABELS: string[] = [
  "alternative",
  "indie",
  "pop",
  "electronic",
  "rock",
  "urban",
  "chill",
  "vibe",
  "mood",
  "vibes",
  "energetic",
  "sad",
  "happy",
  "romantic-generic",
];

// Fallback mapping from the catalog's legacy 8-value broad `genre` field to
// a PrimaryGenre, used only when no other evidence is available. Two
// legacy values are ambiguous and are disambiguated by lane at
// classification time (jazz-funk -> jazz or funk-disco; ambient-dream ->
// rock/dream-pop or ambient-experimental) -- see the Step 3-1 classification
// report in docs/.
export const LEGACY_GENRE_DEFAULT_PRIMARY: Record<string, PrimaryGenre> = {
  "pop": "pop",
  "hip-hop": "hip-hop",
  "rnb-soul": "rnb-soul",
  "rock": "rock",
  "jazz-funk": "jazz",
  "electronic": "electronic",
  "folk-acoustic": "folk-acoustic",
  "ambient-dream": "rock",
};
