// Curation Lane System — 서로 다른 장르 세계관이 한 플레이리스트에 섞이지 않도록
// GPT가 선택할 수 있는 "장르 세계관" 후보를 정의한다.
// 이 리스트는 gpt.ts의 SYSTEM_PROMPT에 텍스트로 변환되어 삽입된다 (출력 schema에는 포함되지 않음).

export type CurationLane = {
  id: string;
  name: string;
  description: string;
  sceneSignals: string[];
  energySignals: string[];
  allowedGenres: string[];
  forbiddenGenres: string[];
  referenceVibes: string[];
  titleExamples: string[];
  avoidWhen: string[];
};

export const CURATION_LANES: CurationLane[] = [
  {
    id: "modern-jazz-groove",
    name: "Modern Jazz Groove",
    description:
      "Beat-driven modern jazz built on live sax, warm Rhodes piano, and laid-back grooves — closer to jazz-hop and neo-soul than traditional swing jazz.",
    sceneSignals: [
      "dim jazz bar with a live sax player",
      "rain streaking a late-night cafe window that also shows a rhythmic lounge/sax/Rhodes-piano or adult-sophisticated nightlife cue (not just any rainy window)",
      "warm Rhodes-piano lounge glow",
      "adult city apartment at night with warm lamp light",
      "stylish rooftop or wine-bar scene after dark",
    ],
    energySignals: ["mellow but rhythmic groove", "sophisticated mid-tempo pulse", "relaxed jazz-club swing", "warm laid-back sax-and-Rhodes feel"],
    allowedGenres: ["nu-jazz", "jazz-hop", "jazz-funk", "neo-soul jazz", "beat-driven jazz fusion", "sax-led instrumental hip-hop"],
    forbiddenGenres: [
      "K-pop",
      "J-rock",
      "anime rock",
      "Japanese alternative rock",
      "high-energy driving rock",
      "pop punk",
      "power pop rock",
      "Britpop",
      "bright dance pop",
      "acoustic cafe pop",
    ],
    referenceVibes: [
      "Harrison & Jaleel Shaw - You Hate Jazz?",
      "Harrison & Jaleel Shaw - All About Us",
      "a live sax solo floating over a steady jazz-hop beat in a dim lounge",
      "warm Rhodes piano chords under a rhythmic, grown-up groove",
    ],
    titleExamples: ["Rain on Rhodes", "Late Night Sax", "Warm Window Grooves"],
    avoidWhen: [
      "the scene calls for bright idol pop energy",
      "the mood is fast highway driving",
      "the setting is a delicate acoustic singer-songwriter cafe",
      "the scene is a sunlit daytime cafe with simple, gentle comfort rather than a rhythmic night groove (prefer Cozy Cafe Mellow instead)",
      "the scene is a solitary late-night car or window mood with smooth R&B sensuality rather than a jazz-club groove (prefer K-R&B Night Drive instead)",
      "the setting is a quiet, empty room with no social/stylish energy (prefer Lo-fi Bedroom Solitude instead)",
      "the scene is simply a rainy late-night window, room, or cafe with no visible jazz/lounge/sax/Rhodes-piano/rhythmic or adult-sophisticated nightlife cue (prefer K-Indie Rainy Room, Cozy Cafe Mellow, or Lo-fi Bedroom Solitude instead, depending on the room and context)",
    ],
  },
  {
    id: "j-rock-highway-rush",
    name: "J-Rock Highway Rush",
    description: "High-speed Japanese rock built for motion — anime-opening energy and driving guitars.",
    sceneSignals: [
      "car or motorcycle in motion on a highway",
      "tunnel lights streaking past",
      "live band performance with guitars",
      "wind-blown hair or clothing suggesting speed",
      "anime-opening-style dynamic action framing",
    ],
    energySignals: ["high-energy adrenaline rush", "fast driving-guitar tempo", "explosive youthful intensity", "propulsive anime-opening pace"],
    allowedGenres: ["J-rock", "anime rock", "Japanese alternative rock", "pop punk", "power pop rock", "high-energy driving rock"],
    forbiddenGenres: ["nu-jazz", "K-R&B", "lo-fi", "slow indie", "acoustic cafe pop", "city pop lounge"],
    referenceVibes: [
      "L'Arc~en~Ciel - Driver's High",
      "anime opening rush",
      "high-speed highway guitars",
      "a motorcycle or car cutting through a tunnel at full speed",
    ],
    titleExamples: ["Blue Sky Highway", "Tunnel Lights Rock", "Summer Road Opening"],
    avoidWhen: [
      "the scene is a quiet indoor room",
      "the mood calls for slow reflective jazz",
      "the setting is a mellow late-night lounge",
      "the scene is a calm Japanese street or landmark with no actual motion, speed, or performance signal (do not choose this lane from cultural cues alone)",
      "the scene is a peaceful sunny travel moment without adrenaline or driving energy (prefer American Alternative Drive or Indie Road Movie instead)",
      "the scene feels like retro city nostalgia rather than raw speed (prefer City Pop / Retro Drive instead)",
    ],
  },
  {
    id: "k-rnb-night-drive",
    name: "K-R&B Night Drive",
    description: "Smooth, moody Korean R&B and late-night electronic pop for neon city nights.",
    sceneSignals: [
      "a single figure walking a neon-lit street at night",
      "rain-streaked car window with city lights blurring past",
      "a lone silhouette against a glowing storefront or apartment window",
      "soft neon reflected on wet pavement",
      "a quiet late-night portrait with moody, low lighting",
      "a static or parked moment — a figure standing still, sitting alone, or seen through a window reflection rather than in motion",
    ],
    energySignals: ["smooth, sensual mid-tempo", "moody but groovy R&B pulse", "late-night electronic softness", "lonely, intimate night energy"],
    allowedGenres: ["K-R&B", "Korean alt R&B", "mellow K-pop", "late-night electronic pop", "Korean city pop"],
    forbiddenGenres: ["J-rock", "folk rock", "post-rock", "bright idol pop", "old jazz"],
    referenceVibes: [
      "neon-lit Seoul streets at 2am",
      "a car window blurring past city lights",
      "smooth Korean R&B vocals floating over soft electronic textures",
      "a single figure alone under neon signage",
    ],
    titleExamples: ["Seoul After Midnight", "Neon Window R&B"],
    avoidWhen: [
      "the scene is a sunny highway road trip",
      "the mood calls for acoustic folk rock",
      "the setting is an old vintage film photo",
      "the scene has aggressive, confident street/rap energy rather than smooth sensuality (prefer Hip-Hop Night Drive instead)",
      "the scene shows a couple or romantic warmth rather than solitary loneliness (prefer Modern Romance Pop instead)",
      "the scene feels tense, menacing, or heavy rather than smooth and moody (prefer Dark Heavy Hip-Hop instead)",
      "the scene shows a moving car mid-cruise, downtown lights streaming past with motion, confident posture, or streetwear/rap energy rather than a static, solo, intimate moment (prefer Hip-Hop Night Drive instead)",
    ],
  },
  {
    id: "k-indie-rainy-room",
    name: "K-Indie Rainy Room",
    description: "Soft, intimate Korean indie and bedroom pop for quiet, ordinary daily-life moments.",
    sceneSignals: [
      "raindrops tracing down a bedroom or living-room window",
      "an ordinary, lived-in room with soft daylight",
      "a half-finished cup of tea or coffee on a small table",
      "a diary, notebook, or houseplant in a quiet domestic space",
      "soft, unstyled everyday clutter rather than a curated cafe",
    ],
    energySignals: ["soft, low-tempo intimacy", "quietly emotional, diary-like warmth", "gentle acoustic stillness with a hint of rain-tapping rhythm"],
    allowedGenres: ["K-indie", "bedroom pop", "soft Korean rock", "acoustic indie", "mellow Korean pop"],
    forbiddenGenres: ["dance pop", "high-speed rock", "heavy electronic", "bright idol pop"],
    referenceVibes: [
      "rain tapping steadily against a bedroom window",
      "a quiet, ordinary room with soft grey daylight",
      "gentle acoustic guitar and breathy, close-mic'd vocals",
      "a handwritten diary entry set to music",
    ],
    titleExamples: ["Rainy Window Diary", "Soft Room Hours"],
    avoidWhen: [
      "the scene is a party or bright social gathering",
      "the mood is high-speed and energetic",
      "the setting calls for funk or disco energy",
      "the scene is outdoor, hazy, or fog-blurred rather than an ordinary indoor room (prefer Dream Pop / Shoegaze Fog instead)",
      "the scene is a private desk or bedroom with no rain or diary-like domestic detail (prefer Lo-fi Bedroom Solitude instead)",
      "the scene is a warm public cafe or bakery rather than a private ordinary room (prefer Cozy Cafe Mellow instead)",
    ],
  },
  {
    id: "city-pop-retro-glow",
    name: "City Pop / Retro Drive",
    description: "Glossy Japanese/Korean city pop and retro funk pop for nostalgic, sun-drenched drives.",
    sceneSignals: [
      "a car windshield reflecting a warm sunset",
      "retro film-grain color grading (warm oranges, faded pastels)",
      "a glossy 1980s-style cityscape at dusk",
      "a highway or waterfront drive bathed in golden-hour light",
      "vintage analog-camera aesthetic with soft warm tones",
    ],
    energySignals: ["upbeat mid-tempo glide", "groovy retro funk pulse", "nostalgic, sun-drenched drive energy", "glossy 80s synth warmth"],
    allowedGenres: ["Japanese city pop", "Korean city pop", "retro pop", "funk pop", "jazz pop"],
    forbiddenGenres: ["heavy rock", "dark trap", "post-rock", "slowcore"],
    referenceVibes: [
      "a sunset reflecting off a car windshield on a coastal highway",
      "retro film-photo color grading with warm analog grain",
      "funky basslines under glossy 80s synths",
      "a glowing skyline at dusk seen through a car window",
    ],
    titleExamples: ["Sunset Drive Tapes", "Retro City Glow"],
    avoidWhen: [
      "the scene is dark and somber",
      "the mood calls for ambient post-rock",
      "the setting is a slow introspective night",
      "the scene is bright open-air ocean/beach/blue-sky daytime with active, breezy vacation energy (prefer Summer Beach Pop or another bright open-air lane instead)",
      "the scene is modern, glossy, fashion-forward, or social-media/mirror-selfie styled rather than retro/nostalgic (prefer Trendy Pop Chic instead)",
      "the scene is a travel/departure story such as a train, airport, or open road rather than a retro city mood (prefer Indie Road Movie instead)",
      "the scene is simply a sunny, ordinary Japanese- or Korean-looking street or window with no retro glow, sunset warmth, or nostalgic signal (do not choose this lane from cultural/location cues alone)",
      "the scene is a quiet warm cafe with plain daytime comfort rather than a sunset drive or retro city-glow mood (prefer Cozy Cafe Mellow instead)",
    ],
  },
  {
    id: "indie-road-movie",
    name: "Indie Road Movie",
    description: "Wistful indie rock and Britpop for travel, departures, and open roads.",
    sceneSignals: [
      "a train pulling away from a platform",
      "an empty airport terminal or departure gate",
      "a solitary figure with a suitcase or backpack",
      "an open road stretching into changing scenery",
      "a bus or train window showing landscape passing by",
    ],
    energySignals: ["mid-tempo, unhurried momentum", "wistful but moving forward", "anthemic yet understated", "quietly cinematic travel pace"],
    allowedGenres: ["indie rock", "Britpop", "folk rock", "soft alternative rock", "road trip songs"],
    forbiddenGenres: ["K-pop dance", "nu-jazz", "dark electronic", "lounge jazz"],
    referenceVibes: [
      "a train pulling out of a station as someone watches from the platform",
      "an open road unfolding through changing scenery",
      "strummed guitars building into a wide-open, understated chorus",
      "a solitary traveler at a departure gate",
    ],
    titleExamples: ["Platform Daydreams", "Departure Lane Indie"],
    avoidWhen: [
      "the scene is a stylish urban night",
      "the mood calls for K-R&B or jazz-hop",
      "the setting is a dance club",
      "the scene has strong speed/adrenaline/guitar-driven rush rather than a wistful pace (prefer J-Rock Highway Rush instead)",
      "the scene shows friends casually enjoying a sunny drive rather than a solitary departure story (prefer American Alternative Drive instead)",
      "the scene feels like retro city nostalgia (sunset drive, glossy synths) rather than a travel/departure narrative (prefer City Pop / Retro Drive instead)",
      "the scene is a plain peaceful outdoor or indoor scenic view — pavilion, mountain, park, nature, city-view, or ocean-view — with no visible road, transit, vehicle, platform, airport, suitcase, or journey narrative; a calm or scenic view alone is never enough to choose this lane, even if the mood reads as nostalgic, wistful, dreamy, or expansive (judge another lane on its own visual evidence instead)",
      "the mood is generically nostalgic, wistful, peaceful, or dreamy but the image shows no departure, transit, vehicle, or road-trip narrative — do not choose this lane from mood words alone",
    ],
  },
  {
    id: "american-alternative-drive",
    name: "American Alternative Drive",
    description: "Sunny, casual American alt rock and garage rock for daytime road energy with friends.",
    sceneSignals: [
      "friends packed into a car with windows down",
      "a sunlit highway with casual, unposed energy",
      "a road trip pit stop or gas station in daylight",
      "sunglasses, denim, or casual summer clothing in motion",
      "a group laughing or singing along in a car",
    ],
    energySignals: ["energetic mid-to-uptempo", "sunny and casual", "garage-rock punch", "carefree group energy"],
    allowedGenres: ["American alt rock", "2000s rock", "garage rock", "pop rock", "highway rock"],
    forbiddenGenres: ["K-R&B", "jazz-hop", "soft cafe pop"],
    referenceVibes: [
      "friends piled into a car with the windows down",
      "a sunlit highway with casual, unhurried energy",
      "crunchy guitars and singalong choruses",
      "a road-trip pit stop in the middle of a sunny afternoon",
    ],
    titleExamples: ["Shotgun Summer", "Highway With Friends"],
    avoidWhen: [
      "the scene is a moody night street",
      "the mood calls for smooth R&B or jazz",
      "the setting is a quiet rainy room",
      "the scene has strong speed/anime/guitar-driven adrenaline rather than casual sunny cruising (prefer J-Rock Highway Rush instead)",
      "the scene is a solitary traveler or a wistful departure story rather than a group of friends (prefer Indie Road Movie instead)",
      "the scene is polished, glossy, or fashion-forward rather than casual and sun-worn (prefer Trendy Pop Chic instead)",
    ],
  },
  {
    id: "dream-pop-shoegaze-fog",
    name: "Dream Pop / Shoegaze Fog",
    description: "Hazy, reverb-soaked dream pop and shoegaze for foggy, blurred, melancholic scenes.",
    sceneSignals: [
      "thick fog blurring a skyline or landscape",
      "soft-focus, washed-out lighting with no sharp edges",
      "distant lights glowing through mist or rain",
      "a figure or object dissolving into haze at the edges of the frame",
      "an overexposed or dreamlike double-exposure look",
    ],
    energySignals: ["slow to mid-tempo drift", "hazy and washed-out", "dreamlike, reverb-soaked stillness", "ethereal, floating pace"],
    allowedGenres: ["dream pop", "shoegaze", "ethereal indie", "reverb-heavy guitar pop", "haze pop"],
    forbiddenGenres: ["bright dance pop", "hard rock", "funk pop"],
    referenceVibes: [
      "fog rolling over a skyline until the lights blur into soft halos",
      "reverb-soaked guitars dissolving into a wall of sound",
      "soft, half-whispered vocals buried in haze",
      "a scene that feels like it's being remembered rather than seen",
    ],
    titleExamples: ["Fog Over the Skyline", "Hazy Light Drift"],
    avoidWhen: [
      "the scene is bright and high-energy",
      "the mood calls for funk or disco",
      "the setting is a sharp, punchy rock scene",
      "the scene is an ordinary rainy room with clear, sharp detail rather than hazy blur (prefer K-Indie Rainy Room instead)",
      "the scene is a plain, minimal bedroom with no fog, haze, or blur (prefer Lo-fi Bedroom Solitude instead)",
      "the scene is bright, sunny, and clear rather than washed-out or misty (prefer Summer Beach Pop instead)",
    ],
  },
  {
    id: "neon-electronic-night",
    name: "Neon Electronic Night",
    description: "Pulsing synthwave and late-night electronic pop for futuristic, neon-lit nights.",
    sceneSignals: [
      "neon signage reflected on wet pavement",
      "a late-night subway car under cold fluorescent or neon light",
      "glowing screens or digital billboards in a night cityscape",
      "a cool blue, purple, or pink neon color palette with hard edges",
      "a futuristic or cyberpunk-styled night street",
    ],
    energySignals: ["pulsing mid-tempo", "synthetic and electric", "cold, futuristic nocturnal energy", "mechanical, screen-lit pace"],
    allowedGenres: ["synthwave", "electronic pop", "darkwave", "late-night electronic", "cyber pop"],
    forbiddenGenres: ["acoustic folk", "oldies", "jazz vocal"],
    referenceVibes: [
      "neon signs reflected on wet pavement",
      "a late subway car lit by cold fluorescent light",
      "pulsing synths and electronic drums under a cyberpunk skyline",
      "glowing digital screens against a dark night street",
    ],
    titleExamples: ["Neon Transit", "Cyber Midnight"],
    avoidWhen: [
      "the scene is acoustic and organic",
      "the mood calls for vintage soul or oldies",
      "the setting is a quiet daytime scene",
      "the scene is a warm, colorful dancefloor or party rather than cold synthetic neon (prefer Funk / Disco Night instead)",
      "the scene is a confident rap cruise or sensual R&B night drive rather than futuristic/cyber energy (prefer Hip-Hop Night Drive or K-R&B Night Drive instead)",
      "the scene feels retro, glossy, and sunset-warm rather than cold and futuristic (prefer City Pop / Retro Drive instead)",
    ],
  },
  {
    id: "lofi-bedroom-solitude",
    name: "Lo-fi Bedroom Solitude",
    description: "Minimal lo-fi and slowcore for solitary, introspective indoor moments.",
    sceneSignals: [
      "a desk lamp glowing in an otherwise dark room",
      "headphones on a desk or worn by a solitary figure",
      "a laptop or notebook lit only by screen glow",
      "a plain, minimally decorated private room at night",
      "a single unmade bed or quiet nighttime bedroom with no one else present",
      "a private, quiet home selfie or personal desk/bedroom moment alone with low energy and no cafe, party, or youthful/poster styling",
    ],
    energySignals: ["very low tempo, minimal beats", "introspective, unhurried stillness", "soft tape-hiss quietness", "solitary, unbothered pace"],
    allowedGenres: ["lo-fi", "bedroom pop", "slowcore", "soft melancholy indie", "minimal beats"],
    forbiddenGenres: ["high-energy rock", "bright K-pop", "funk pop"],
    referenceVibes: [
      "a desk lamp glowing alone in a dim room",
      "soft tape-hiss beats looping quietly at 1am",
      "a single figure with headphones on, undisturbed",
      "the quiet hum of a laptop screen in an otherwise dark room",
    ],
    titleExamples: ["Desk Lamp Hours", "Quiet Tape Nights"],
    avoidWhen: [
      "the scene is high-energy or social",
      "the mood calls for driving rock or bright pop",
      "the setting is an outdoor party",
      "the scene is a warm public cafe or bakery with daylight rather than a private night room (prefer Cozy Cafe Mellow instead)",
      "the scene shows rain against a window with a soft diary-like domestic feeling (prefer K-Indie Rainy Room instead)",
      "the scene shows a youthful bedroom with posters, friends, or school energy rather than quiet solitude (prefer Highteen Pop Room instead)",
    ],
  },
  {
    id: "summer-beach-pop",
    name: "Summer Beach Pop",
    description: "Bright surf rock and sunny pop for beach days and vacation energy.",
    sceneSignals: [
      "ocean waves or a beach shoreline under a clear blue sky",
      "a pool or open-water scene in bright daylight",
      "sunglasses, swimwear, or vacation gear in direct sunlight",
      "a wide-open harbor, coastline, or seaside horizon",
      "bright midday sun with minimal shadow, no golden-hour warmth",
    ],
    energySignals: ["upbeat, sun-soaked energy", "bright and breezy pace", "light, active midday vacation feel"],
    allowedGenres: ["surf rock", "summer K-pop", "tropical indie", "bright J-pop", "sunny pop rock"],
    forbiddenGenres: ["slowcore", "darkwave", "noir jazz"],
    referenceVibes: [
      "waves rolling onto a sunny beach under a clear blue sky",
      "a bright open harbor or coastline at midday",
      "breezy surf guitars and light percussion",
      "sunglasses and salt air on an open-water vacation",
    ],
    titleExamples: ["Blue Wave Summer", "Sunlit Shoreline"],
    avoidWhen: [
      "the scene is dark or moody",
      "the mood calls for slowcore or noir jazz",
      "the setting is a rainy indoor room",
      "the scene is a golden-hour/sunset city drive with retro nostalgia rather than bright midday openness (prefer City Pop / Retro Drive instead)",
      "the scene is an indoor fashion/editorial shoot rather than an actual open-air water/beach scene (prefer Trendy Pop Chic instead)",
      "the scene is a travel/departure story (train, airport, road) without beach/sun/water energy (prefer Indie Road Movie instead)",
      "the scene is merely a sunny street, city block, or clear-sky daytime scene with no visible ocean, beach, pool, harbor, or open-air vacation/leisure cue — bright sunlight or a clear sky alone is never enough to choose this lane (judge other lanes on their own signals instead)",
    ],
  },
  {
    id: "funk-disco-night",
    name: "Funk / Disco Night",
    description: "Groovy disco and funk for stylish, danceable nights out.",
    sceneSignals: [
      "a colorful, warm-lit dancefloor with people dancing",
      "disco ball or warm party lighting (reds, golds, pinks)",
      "a group of friends dancing or celebrating together",
      "a retro-styled nightclub or house-party scene",
      "warm, saturated colored lighting rather than cool neon",
    ],
    energySignals: ["groovy, danceable uptempo", "warm, stylish, confident party energy", "four-on-the-floor social groove"],
    allowedGenres: ["disco", "funk", "city funk", "danceable retro grooves", "nu-disco"],
    forbiddenGenres: ["acoustic folk", "post-rock", "slowcore"],
    referenceVibes: [
      "colorful, warm nightclub lighting over a packed dancefloor",
      "a night out with friends dancing together",
      "funky basslines and four-on-the-floor grooves",
      "a disco ball scattering warm light across a party",
    ],
    titleExamples: ["Disco Lights Tonight", "Funk on the Floor"],
    avoidWhen: [
      "the scene is quiet and introspective",
      "the mood calls for acoustic folk",
      "the setting is a slow rainy day",
      "the scene is cool, synthetic, and futuristic rather than warm and colorful (prefer Neon Electronic Night instead)",
      "the scene is a stylish lounge or jazz-bar groove without an actual dancefloor or party (prefer Modern Jazz Groove instead)",
      "the scene feels dark, tense, or aggressive rather than warm and social (prefer Dark Heavy Hip-Hop instead)",
    ],
  },
  {
    id: "classic-soul-old-film",
    name: "Classic Soul / Old Film",
    description: "Warm classic soul and vintage ballads for nostalgic, old-film-toned scenes.",
    sceneSignals: [
      "a faded, grainy old photograph or home-movie still",
      "warm sepia or film-grain color toning",
      "a vintage family gathering or old street scene",
      "analog film artifacts (light leaks, scratches, soft focus)",
      "clothing or decor that reads as decades-old rather than 80s-glossy",
    ],
    energySignals: ["warm, soulful mid-tempo", "nostalgic, unhurried warmth", "timeless, horn-and-vocal-driven feel"],
    allowedGenres: ["classic soul", "oldies", "Motown-like pop", "vintage ballads", "warm retro soul"],
    forbiddenGenres: ["anime rock", "synthwave", "bright idol pop"],
    referenceVibes: [
      "a faded family photograph with warm sepia tones",
      "an old film camera's warm grain and light leaks",
      "soulful vocals over warm horns",
      "a decades-old home movie still, quietly nostalgic",
    ],
    titleExamples: ["Old Film Soul", "Faded Photograph Motown"],
    avoidWhen: [
      "the scene is a futuristic neon night",
      "the mood calls for anime rock or synthwave",
      "the setting is a bright modern K-pop scene",
      "the scene has 80s-glossy synth/sunset-drive energy rather than old-film analog warmth (prefer City Pop / Retro Drive instead)",
      "the scene is a modern, polished editorial/fashion moment rather than a faded vintage photograph feel (prefer Trendy Pop Chic instead)",
      "the scene is bright, open-air, and sunny/vacation-like rather than warmly nostalgic (prefer Summer Beach Pop instead)",
    ],
  },
  {
    id: "big-city-swagger-hiphop",
    name: "Big City Swagger Hip-Hop",
    description:
      "Confident, bass-heavy hip-hop rooted in classic and modern rap swagger — black cars, skylines, and big-city dominance energy.",
    sceneSignals: [
      "a black luxury car gliding past a glowing skyline",
      "a confident figure standing tall against a downtown backdrop",
      "a rooftop or high-rise view of a city skyline at night",
      "designer or luxury styling cues (watches, sneakers, tailored fits)",
      "a wide, dominant low-angle shot of city architecture",
    ],
    energySignals: ["confident, mid-to-high bass-driven energy", "swaggering, unhurried groove", "dominant, luxury-flex pace"],
    allowedGenres: ["east-coast hip-hop", "west-coast hip-hop", "luxury rap", "trap", "mainstream rap"],
    forbiddenGenres: ["K-pop", "J-rock", "soft acoustic pop", "ambient"],
    referenceVibes: [
      "Nas - N.Y. State of Mind",
      "JAY-Z - U Don't Know",
      "a black car gliding past a glowing skyline",
      "a confident figure owning a downtown skyline at night",
    ],
    titleExamples: ["Skyline Flex", "Downtown Black Car"],
    avoidWhen: [
      "the scene is a quiet rainy room",
      "the mood calls for soft acoustic pop",
      "the setting is a bright K-pop moment",
      "the scene has smooth, melodic, low-key cruise energy rather than confident dominance (prefer Hip-Hop Night Drive instead)",
      "the scene feels tense, menacing, or underground rather than confident and luxurious (prefer Dark Heavy Hip-Hop instead)",
      "the scene is synthetic, futuristic, or neon-electronic rather than a real skyline/luxury-car scene (prefer Neon Electronic Night instead)",
    ],
  },
  {
    id: "highteen-pop-room",
    name: "Highteen Pop Room",
    description: "Bedroom pop and teen-pop energy for highschool bedrooms, selfies, and youthful drama.",
    sceneSignals: [
      "a teenage bedroom with posters, fairy lights, or plush toys",
      "a school hallway or locker scene",
      "friends laughing together in a casual, youthful setting",
      "a playful selfie with bright, unpolished styling",
      "handwritten notes, stickers, or DIY decor",
      "a casual home selfie with youthful, poster, friends, school, or cute/playful energy rather than polished editorial fashion",
    ],
    energySignals: ["playful, mid-to-high tempo bounce", "bright and dramatic teen energy", "youthful, unfiltered enthusiasm"],
    allowedGenres: ["bedroom pop", "teen pop", "pop rock", "indie pop"],
    forbiddenGenres: ["dark trap", "post-rock", "noir jazz"],
    referenceVibes: [
      "Olivia Rodrigo - good 4 u",
      "Conan Gray - Maniac",
      "a teenage bedroom full of posters and fairy lights",
      "friends giggling together after school",
    ],
    titleExamples: ["Locker Room Drama", "Pink Room Diaries"],
    avoidWhen: [
      "the scene is a moody adult night",
      "the mood calls for dark or heavy hip-hop",
      "the setting is a formal or mature scene",
      "the scene is a polished, editorial, adult-fashion moment rather than playful teen energy (prefer Trendy Pop Chic instead)",
      "the scene shows one person alone in quiet stillness rather than youthful social energy (prefer Lo-fi Bedroom Solitude instead)",
      "the scene reads as a romantic date rather than friend or school energy (prefer Modern Romance Pop instead)",
    ],
  },
  {
    id: "modern-romance-pop",
    name: "Modern Romance Pop",
    description: "Glowing synth-pop and modern romance for night drives, date nights, and bittersweet young love.",
    sceneSignals: [
      "two people together in a warm, intimate moment",
      "a date-night scene with soft glowing light",
      "hands touching or close physical closeness between two people",
      "a rainy street or city window shared by a couple",
      "a phone-lit face suggesting a late-night conversation with someone",
    ],
    energySignals: ["mid-tempo, glowing and emotional", "romantic, gentle pulse", "bittersweet but hopeful warmth"],
    allowedGenres: ["synth-pop", "modern pop", "indie pop", "electro-soul"],
    forbiddenGenres: ["heavy trap", "post-rock", "classic jazz"],
    referenceVibes: [
      "LANY - ILYSB",
      "The 1975 - Robbers",
      "city lights blurring past a car window shared by two people",
      "a quiet, glowing conversation between two people at night",
    ],
    titleExamples: ["City Lights Romance", "Night Drive Confession"],
    avoidWhen: [
      "the scene is a chaotic party",
      "the mood calls for aggressive hip-hop",
      "the setting is a bright daytime beach",
      "the scene shows one person alone rather than a couple or shared intimacy (prefer K-R&B Night Drive instead)",
      "the scene is bright, open-air vacation energy rather than an intimate glow (prefer Summer Beach Pop instead)",
      "the scene shows a group of friends rather than a romantic pair (prefer Highteen Pop Room or American Alternative Drive instead)",
    ],
  },
  {
    id: "trendy-pop-chic",
    name: "Trendy Pop Chic",
    description: "Glossy, confident K-pop and modern pop for fashion-forward, stylish city moments.",
    sceneSignals: [
      "a mirror selfie in a styled, curated outfit",
      "an editorial-style portrait with clean, modern lighting",
      "a fashion-forward look on a city street",
      "polished, high-contrast, social-media-ready framing",
      "designer or trend-driven styling with minimal clutter",
      "a polished home or mirror selfie with fashion/makeup/editorial confidence, even indoors or at home",
    ],
    energySignals: ["confident, mid-to-high polished tempo", "sleek and trend-driven energy", "clean, camera-ready confidence"],
    allowedGenres: ["K-pop", "trendy pop", "fashion pop", "hyper-pop"],
    forbiddenGenres: ["lo-fi", "post-rock", "old jazz"],
    referenceVibes: [
      "NewJeans - Super Shy",
      "LE SSERAFIM - Perfect Night",
      "a mirror selfie in a stylish outfit on a clean city street",
      "a polished editorial portrait with modern, glossy lighting",
    ],
    titleExamples: ["Mirror Selfie Chic", "Neon Runway Pop"],
    avoidWhen: [
      "the scene is a quiet solitary room",
      "the mood calls for ambient or ballad energy",
      "the setting is a rainy melancholic day",
      "the scene is a playful teenage bedroom or school setting rather than adult editorial polish (prefer Highteen Pop Room instead)",
      "the scene feels retro, nostalgic, or sunset-glow rather than modern and glossy (prefer City Pop / Retro Drive instead)",
      "the scene is a plain, unstyled casual home selfie with no fashion/makeup/editorial polish — youthful/poster/friends/school/cute energy points to Highteen Pop Room instead, and a quiet/private/alone low-energy moment points to Lo-fi Bedroom Solitude instead",
    ],
  },
  {
    id: "cozy-cafe-mellow",
    name: "Cozy Cafe Mellow",
    description: "Warm, gentle soul-pop and soft R&B for sunlit cafe windows and easygoing daytime moments.",
    sceneSignals: [
      "a window-seat table with a coffee cup in soft daylight",
      "a bakery counter or pastry display",
      "warm morning or early-afternoon sunlight across a cafe table",
      "a book, laptop, or journal on a public cafe table",
      "gentle, unhurried public seating rather than a private room",
    ],
    energySignals: ["gentle, low-to-mid tempo", "warm, easygoing daytime calm", "soft, unrushed public comfort"],
    allowedGenres: ["jazz pop", "soul pop", "mellow R&B", "k-indie cafe pop"],
    forbiddenGenres: ["dark trap", "synthwave", "hard rock"],
    referenceVibes: [
      "Norah Jones - Don't Know Why",
      "Corinne Bailey Rae - Put Your Records On",
      "warm sunlight falling across a cafe table",
      "a quiet window-seat morning with a coffee cup nearby",
    ],
    titleExamples: ["Window Seat Mornings", "Sunlit Cafe Hours"],
    avoidWhen: [
      "the scene is a dark night street",
      "the mood calls for aggressive or heavy energy",
      "the setting is a neon nightclub",
      "the scene has a rhythmic, stylish night-lounge groove rather than gentle daytime comfort (prefer Modern Jazz Groove instead)",
      "the scene is a private bedroom or desk with no public cafe setting (prefer Lo-fi Bedroom Solitude instead)",
      "the scene shows rain against a window with a soft diary-like domestic mood rather than a cafe table (prefer K-Indie Rainy Room instead)",
      "the scene is a private home, bedroom, or personal selfie with no visible cafe, bakery, coffee cup, public table, or window-seat cue — warm daylight alone is never enough to choose this lane (prefer Lo-fi Bedroom Solitude for quiet/private moments, Highteen Pop Room for youthful/casual home selfies, or Trendy Pop Chic for polished/editorial home selfies instead)",
    ],
  },
  {
    id: "hip-hop-night-drive",
    name: "Hip-Hop Night Drive",
    description: "Smooth, melodic Korean hip-hop and R&B-rap for neon night drives and late-night city cruising.",
    sceneSignals: [
      "a car interior lit by passing streetlights at night",
      "downtown city lights streaming past a car window",
      "a confident but relaxed nighttime cruise through the city",
      "neon signage blurred by motion through a windshield",
      "a late-night city street with moderate, moving energy rather than stillness",
      "clear motion — a moving car, cruising downtown, confident posture, or streetwear styling rather than a parked/static moment",
    ],
    energySignals: ["smooth, melodic mid-tempo", "rhythmic but relaxed cruise energy", "confident, late-night groove"],
    allowedGenres: ["K-hip-hop", "melodic rap", "alt R&B-rap", "chill trap"],
    forbiddenGenres: ["bright idol pop", "acoustic folk", "classic jazz"],
    referenceVibes: [
      "DPR LIVE - Jasmine",
      "Beenzino - If I Die Tomorrow",
      "neon city lights streaming past a car window at night",
      "a smooth, confident late-night cruise through downtown",
    ],
    titleExamples: ["Neon Cruise Rap", "Late Night City Flow"],
    avoidWhen: [
      "the scene is a bright daytime scene",
      "the mood calls for acoustic or folk energy",
      "the setting is a sunny beach",
      "the scene is soft, lonely, and sensual rather than a confident rap cruise (prefer K-R&B Night Drive instead)",
      "the scene feels tense, menacing, or underground rather than smooth and relaxed (prefer Dark Heavy Hip-Hop instead)",
      "the scene shows luxury/skyline dominance and stillness rather than an in-motion cruise (prefer Big City Swagger Hip-Hop instead)",
      "the scene is static, parked, or intimate — a solo figure standing still, soft neon reflection, window/glass reflection, or a lonely stationary mood rather than in-motion cruise energy (prefer K-R&B Night Drive instead)",
    ],
  },
  {
    id: "dark-heavy-hiphop",
    name: "Dark Heavy Hip-Hop",
    description: "Aggressive, bass-heavy trap and drill for dark, tense, high-stakes night scenes.",
    sceneSignals: [
      "a shadowy, underlit street or alley",
      "a black room lit only by a phone screen",
      "an aggressive pose or intense, confrontational expression",
      "underground or graffiti-heavy urban texture",
      "harsh, low-key lighting with deep shadow rather than glow",
    ],
    energySignals: ["heavy, tense, bass-driven intensity", "aggressive mid-to-high energy", "underground, menacing pace"],
    allowedGenres: ["trap", "drill", "dark hip-hop", "rage rap"],
    forbiddenGenres: ["acoustic folk", "soft cafe pop", "bright K-pop"],
    referenceVibes: [
      "Travis Scott - goosebumps",
      "Pop Smoke - Dior",
      "a black room lit only by a phone screen and shadow",
      "a shadowy underground street with heavy bass energy",
    ],
    titleExamples: ["Shadow City Trap", "Underground Pressure"],
    avoidWhen: [
      "the scene is bright and cheerful",
      "the mood calls for soft acoustic or cafe pop",
      "the setting is a sunny beach day",
      "the scene is smooth and relaxed rather than tense and aggressive (prefer Hip-Hop Night Drive instead)",
      "the scene shows confident luxury or skyline dominance without menace or shadow (prefer Big City Swagger Hip-Hop instead)",
      "the scene is synthetic or futuristic neon rather than dark and underground (prefer Neon Electronic Night instead)",
    ],
  },
  {
    id: "sunny-stroll-pop",
    name: "Sunny Stroll Pop",
    description:
      "Bright, charming daytime pop for sunny walks through flowers, gardens, neighborhood alleys, plants, cats, bicycles, blue skies, and colorful everyday scenery.",
    sceneSignals: [
      "bright flowers or blossoms in daylight",
      "a spring garden or sunny park",
      "a clear blue sky with visible greenery or plants",
      "colorful daylight plants along a street",
      "a residential alley with flower pots",
      "a small neighborhood street in daylight",
      "a garden path or sunlit sidewalk",
      "a bicycle near plants or flowers",
      "a cat in a sunny alley",
      "a small local shop exterior in daylight",
      "cute everyday outdoor details (flower pots, plants, small signage, quiet local corners)",
      "fresh spring or early-summer daylight air",
      "a pavilion, mountain, or open green outdoor view — only when the mood feels cheerful, bright, and stroll-like rather than lonely, epic, or travel-like",
    ],
    energySignals: [
      "light movement, walking/strolling feeling",
      "cheerful daytime energy",
      "fresh breeze, playful bounce",
      "cute everyday liveliness",
      "bright calm-to-medium energy — not festival-level energy",
    ],
    allowedGenres: [
      "bright pop",
      "singer-songwriter pop",
      "quirky piano pop",
      "sunny guitar pop",
      "light city pop",
      "playful indie pop",
      "soft funk-pop",
      "cheerful alt-pop",
      "fresh Korean pop",
      "fresh Japanese pop",
      "breezy English indie pop",
    ],
    forbiddenGenres: [
      "dark shoegaze",
      "melancholic bedroom pop",
      "foggy dream pop",
      "rainy night music",
      "heavy rock",
      "trap",
      "hip-hop swagger",
      "dark R&B",
      "neon club/electronic intensity",
      "overly acoustic cafe-only mellow music",
      "overly romantic ballads",
      "beach-party-only tropical pop",
      "fashion/editorial pop",
    ],
    referenceVibes: [
      "TOMOO - Ginger",
      "TOMOO - LUCKY",
      "a colorful sunny neighborhood walk",
      "cute everyday daylight — flower pots, cats, bikes, plants, blue sky",
      "bright, playful pop — not beach party, not cafe mellow, not dark dream-pop",
    ],
    titleExamples: ["Sunny Stroll Pop", "Blooming Side Street", "Garden Alley Pop", "Bright Day Walk", "Little Sunny Things"],
    avoidWhen: [
      "ocean, beach, pool, surf, harbor, or vacation water dominates the scene (prefer Summer Beach Pop instead)",
      "cafe, coffee, bakery, table, or indoor window-seat comfort dominates the scene (prefer Cozy Cafe Mellow instead)",
      "fashion, editorial, styling, or city-chic subject dominates the scene (prefer Trendy Pop Chic instead)",
      "bedroom, selfie, friends, or teen room interior dominates the scene (prefer Highteen Pop Room instead)",
      "couple, date, or romantic intimacy dominates the scene (prefer Modern Romance Pop instead)",
      "road, vehicle, airport, train, departure, travel journey, wide empty road, or nostalgic road-trip mood dominates the scene (prefer Indie Road Movie or American Alternative Drive instead)",
      "fog, haze, mist, blur, washed-out gray light, rainy glass, or low-contrast melancholy dominates the scene (prefer Dream Pop / Shoegaze Fog instead)",
      "night, neon, or city nightlife dominates the scene (prefer a night lane — Neon Electronic Night, K-R&B Night Drive, or Hip-Hop Night Drive — instead)",
    ],
  },
];

const LANE_NAME_BY_ID = new Map(CURATION_LANES.map((lane) => [lane.id, lane.name]));

// GPT가 선택한 primary_lane_id로 lane name을 조회 — DB에 사람이 읽을 수 있는 이름도 함께 저장하기 위함.
export function getCurationLaneName(laneId: string): string | null {
  return LANE_NAME_BY_ID.get(laneId) ?? null;
}
