// Curation Lane System — 서로 다른 장르 세계관이 한 플레이리스트에 섞이지 않도록
// GPT가 선택할 수 있는 "장르 세계관" 후보를 정의한다.
// 이 리스트는 gpt.ts의 SYSTEM_PROMPT에 텍스트로 변환되어 삽입된다 (출력 schema에는 포함되지 않음).

export type CurationLane = {
  id: string;
  name: string;
  description: string;
  sceneSignals: string[];
  energySignals: string[];
  allowedGenres: string[];
  forbiddenGenres: string[];
  referenceVibes: string[];
  titleExamples: string[];
  avoidWhen: string[];
};

export const CURATION_LANES: CurationLane[] = [
  {
    id: "modern-jazz-groove",
    name: "Modern Jazz Groove",
    description:
      "Beat-driven modern jazz built on live sax, warm Rhodes piano, and laid-back grooves — closer to jazz-hop and neo-soul than traditional swing jazz.",
    sceneSignals: ["rainy cafe", "late-night city", "warm indoor light", "stylish lounge", "quiet reflective mood"],
    energySignals: ["mellow", "groovy mid-tempo", "relaxed but rhythmic", "warm and laid-back"],
    allowedGenres: ["nu-jazz", "jazz-hop", "jazz-funk", "neo-soul jazz", "beat-driven jazz fusion", "sax-led instrumental hip-hop"],
    forbiddenGenres: [
      "K-pop",
      "J-rock",
      "anime rock",
      "Japanese alternative rock",
      "high-energy driving rock",
      "pop punk",
      "power pop rock",
      "Britpop",
      "bright dance pop",
      "acoustic cafe pop",
    ],
    referenceVibes: [
      "Harrison & Jaleel Shaw - You Hate Jazz?",
      "Harrison & Jaleel Shaw - All About Us",
      "warm Rhodes piano over a steady beat",
      "live sax floating over a mellow groove",
    ],
    titleExamples: ["Rain on Rhodes", "Late Night Sax", "Warm Window Grooves"],
    avoidWhen: [
      "the scene calls for bright idol pop energy",
      "the mood is fast highway driving",
      "the setting is a delicate acoustic singer-songwriter cafe",
    ],
  },
  {
    id: "j-rock-highway-rush",
    name: "J-Rock Highway Rush",
    description: "High-speed Japanese rock built for motion — anime-opening energy and driving guitars.",
    sceneSignals: ["highway", "tunnel", "road trip", "blue sky driving", "youthful energy", "speed", "wind", "summer road"],
    energySignals: ["high-energy", "fast tempo", "driving guitars", "adrenaline-rush"],
    allowedGenres: ["J-rock", "anime rock", "Japanese alternative rock", "pop punk", "power pop rock", "high-energy driving rock"],
    forbiddenGenres: ["nu-jazz", "K-R&B", "lo-fi", "slow indie", "acoustic cafe pop", "city pop lounge"],
    referenceVibes: ["L'Arc~en~Ciel - Driver's High", "anime opening rush", "high-speed highway guitars"],
    titleExamples: ["Blue Sky Highway", "Tunnel Lights Rock", "Summer Road Opening"],
    avoidWhen: [
      "the scene is a quiet indoor room",
      "the mood calls for slow reflective jazz",
      "the setting is a mellow late-night lounge",
    ],
  },
  {
    id: "k-rnb-night-drive",
    name: "K-R&B Night Drive",
    description: "Smooth, moody Korean R&B and late-night electronic pop for neon city nights.",
    sceneSignals: ["Seoul night", "neon street", "car window", "lonely city walk", "stylish portrait"],
    energySignals: ["smooth mid-tempo", "moody but groovy", "late-night electronic pulse"],
    allowedGenres: ["K-R&B", "Korean alt R&B", "mellow K-pop", "late-night electronic pop", "Korean city pop"],
    forbiddenGenres: ["J-rock", "folk rock", "post-rock", "bright idol pop", "old jazz"],
    referenceVibes: ["neon-lit Seoul streets", "car window city lights", "smooth Korean R&B vocals over electronic textures"],
    titleExamples: ["Seoul After Midnight", "Neon Window R&B"],
    avoidWhen: [
      "the scene is a sunny highway road trip",
      "the mood calls for acoustic folk rock",
      "the setting is an old vintage film photo",
    ],
  },
  {
    id: "k-indie-rainy-room",
    name: "K-Indie Rainy Room",
    description: "Soft, intimate Korean indie and bedroom pop for quiet, ordinary daily-life moments.",
    sceneSignals: ["rainy window", "quiet room", "cafe", "ordinary daily life", "soft sadness"],
    energySignals: ["soft low-tempo", "intimate", "quietly emotional"],
    allowedGenres: ["K-indie", "bedroom pop", "soft Korean rock", "acoustic indie", "mellow Korean pop"],
    forbiddenGenres: ["dance pop", "high-speed rock", "heavy electronic", "bright idol pop"],
    referenceVibes: ["rain tapping a window", "a quiet bedroom with soft daylight", "gentle acoustic guitar and breathy vocals"],
    titleExamples: ["Rainy Window Diary", "Soft Room Hours"],
    avoidWhen: [
      "the scene is a party or bright social gathering",
      "the mood is high-speed and energetic",
      "the setting calls for funk or disco energy",
    ],
  },
  {
    id: "city-pop-retro-glow",
    name: "City Pop / Retro Drive",
    description: "Glossy Japanese/Korean city pop and retro funk pop for nostalgic, sun-drenched drives.",
    sceneSignals: ["sunset drive", "retro colors", "summer city", "film photo", "nostalgic street"],
    energySignals: ["upbeat mid-tempo", "groovy retro funk", "nostalgic glide"],
    allowedGenres: ["Japanese city pop", "Korean city pop", "retro pop", "funk pop", "jazz pop"],
    forbiddenGenres: ["heavy rock", "dark trap", "post-rock", "slowcore"],
    referenceVibes: ["sunset reflecting off car windows", "retro film-photo color grading", "funky basslines with glossy synths"],
    titleExamples: ["Sunset Drive Tapes", "Retro City Glow"],
    avoidWhen: [
      "the scene is dark and somber",
      "the mood calls for ambient post-rock",
      "the setting is a slow introspective night",
    ],
  },
  {
    id: "indie-road-movie",
    name: "Indie Road Movie",
    description: "Wistful indie rock and Britpop for travel, departures, and open roads.",
    sceneSignals: ["train station", "airport", "bus", "travel", "open road", "leaving somewhere"],
    energySignals: ["mid-tempo", "wistful but moving forward", "anthemic but understated"],
    allowedGenres: ["indie rock", "Britpop", "folk rock", "soft alternative rock", "road trip songs"],
    forbiddenGenres: ["K-pop dance", "nu-jazz", "dark electronic", "lounge jazz"],
    referenceVibes: ["a train pulling out of a station", "open road through changing scenery", "strummed guitars and wide open choruses"],
    titleExamples: ["Platform Daydreams", "Departure Lane Indie"],
    avoidWhen: [
      "the scene is a stylish urban night",
      "the mood calls for K-R&B or jazz-hop",
      "the setting is a dance club",
    ],
  },
  {
    id: "american-alternative-drive",
    name: "American Alternative Drive",
    description: "Sunny, casual American alt rock and garage rock for daytime road energy with friends.",
    sceneSignals: ["road", "friends", "movement", "sunlight", "casual youth energy"],
    energySignals: ["energetic mid-to-uptempo", "sunny and casual", "garage-rock punch"],
    allowedGenres: ["American alt rock", "2000s rock", "garage rock", "pop rock", "highway rock"],
    forbiddenGenres: ["K-R&B", "jazz-hop", "soft cafe pop"],
    referenceVibes: ["friends piled into a car", "sunlit highway with the windows down", "crunchy guitars and singalong choruses"],
    titleExamples: ["Shotgun Summer", "Highway With Friends"],
    avoidWhen: [
      "the scene is a moody night street",
      "the mood calls for smooth R&B or jazz",
      "the setting is a quiet rainy room",
    ],
  },
  {
    id: "dream-pop-shoegaze-fog",
    name: "Dream Pop / Shoegaze Fog",
    description: "Hazy, reverb-soaked dream pop and shoegaze for foggy, blurred, melancholic scenes.",
    sceneSignals: ["fog", "rain", "blurry city", "distant lights", "soft melancholy"],
    energySignals: ["slow to mid-tempo", "hazy and washed-out", "dreamlike drift"],
    allowedGenres: ["dream pop", "shoegaze", "ethereal indie", "reverb-heavy guitar pop", "haze pop"],
    forbiddenGenres: ["bright dance pop", "hard rock", "funk pop"],
    referenceVibes: ["fog rolling over distant city lights", "reverb-soaked guitars blurring into a wall of sound", "soft, half-whispered vocals"],
    titleExamples: ["Fog Over the Skyline", "Hazy Light Drift"],
    avoidWhen: [
      "the scene is bright and high-energy",
      "the mood calls for funk or disco",
      "the setting is a sharp, punchy rock scene",
    ],
  },
  {
    id: "neon-electronic-night",
    name: "Neon Electronic Night",
    description: "Pulsing synthwave and late-night electronic pop for futuristic, neon-lit nights.",
    sceneSignals: ["neon", "city night", "screens", "futuristic mood", "late subway"],
    energySignals: ["pulsing mid-tempo", "synthetic and electric", "nocturnal energy"],
    allowedGenres: ["synthwave", "electronic pop", "darkwave", "late-night electronic", "cyber pop"],
    forbiddenGenres: ["acoustic folk", "oldies", "jazz vocal"],
    referenceVibes: ["neon signs reflected on wet pavement", "a late subway car under fluorescent light", "pulsing synths and electronic drums"],
    titleExamples: ["Neon Transit", "Cyber Midnight"],
    avoidWhen: [
      "the scene is acoustic and organic",
      "the mood calls for vintage soul or oldies",
      "the setting is a quiet daytime scene",
    ],
  },
  {
    id: "lofi-bedroom-solitude",
    name: "Lo-fi Bedroom Solitude",
    description: "Minimal lo-fi and slowcore for solitary, introspective indoor moments.",
    sceneSignals: ["alone in room", "desk", "dim light", "quiet night", "introspection"],
    energySignals: ["very low tempo", "minimal and soft", "introspective stillness"],
    allowedGenres: ["lo-fi", "bedroom pop", "slowcore", "soft melancholy indie", "minimal beats"],
    forbiddenGenres: ["high-energy rock", "bright K-pop", "funk pop"],
    referenceVibes: ["a desk lamp glowing in a dim room", "soft tape-hiss beats", "quiet, unhurried solitude"],
    titleExamples: ["Desk Lamp Hours", "Quiet Tape Nights"],
    avoidWhen: [
      "the scene is high-energy or social",
      "the mood calls for driving rock or bright pop",
      "the setting is an outdoor party",
    ],
  },
  {
    id: "summer-beach-pop",
    name: "Summer Beach Pop",
    description: "Bright surf rock and sunny pop for beach days and vacation energy.",
    sceneSignals: ["beach", "summer", "sunlight", "blue sky", "vacation"],
    energySignals: ["upbeat", "bright and breezy", "sun-soaked energy"],
    allowedGenres: ["surf rock", "summer K-pop", "tropical indie", "bright J-pop", "sunny pop rock"],
    forbiddenGenres: ["slowcore", "darkwave", "noir jazz"],
    referenceVibes: ["waves rolling onto a sunny beach", "bright blue sky over a vacation scene", "breezy surf guitars and light percussion"],
    titleExamples: ["Blue Wave Summer", "Sunlit Shoreline"],
    avoidWhen: [
      "the scene is dark or moody",
      "the mood calls for slowcore or noir jazz",
      "the setting is a rainy indoor room",
    ],
  },
  {
    id: "funk-disco-night",
    name: "Funk / Disco Night",
    description: "Groovy disco and funk for stylish, danceable nights out.",
    sceneSignals: ["night out", "party", "colorful lights", "stylish energy"],
    energySignals: ["groovy uptempo", "danceable", "stylish and confident"],
    allowedGenres: ["disco", "funk", "city funk", "danceable retro grooves", "nu-disco"],
    forbiddenGenres: ["acoustic folk", "post-rock", "slowcore"],
    referenceVibes: ["colorful nightclub lighting", "a night out with friends", "funky basslines and four-on-the-floor grooves"],
    titleExamples: ["Disco Lights Tonight", "Funk on the Floor"],
    avoidWhen: [
      "the scene is quiet and introspective",
      "the mood calls for acoustic folk",
      "the setting is a slow rainy day",
    ],
  },
  {
    id: "classic-soul-old-film",
    name: "Classic Soul / Old Film",
    description: "Warm classic soul and vintage ballads for nostalgic, old-film-toned scenes.",
    sceneSignals: ["old film look", "vintage street", "warm nostalgia", "family photos"],
    energySignals: ["warm mid-tempo", "soulful", "nostalgic warmth"],
    allowedGenres: ["classic soul", "oldies", "Motown-like pop", "vintage ballads", "warm retro soul"],
    forbiddenGenres: ["anime rock", "synthwave", "bright idol pop"],
    referenceVibes: ["a faded family photograph", "an old film camera's warm grain", "soulful vocals over warm horns"],
    titleExamples: ["Old Film Soul", "Faded Photograph Motown"],
    avoidWhen: [
      "the scene is a futuristic neon night",
      "the mood calls for anime rock or synthwave",
      "the setting is a bright modern K-pop scene",
    ],
  },
  {
    id: "big-city-swagger-hiphop",
    name: "Big City Swagger Hip-Hop",
    description:
      "Confident, bass-heavy hip-hop rooted in classic and modern rap swagger — black cars, skylines, and big-city dominance energy.",
    sceneSignals: ["skyline", "black car", "downtown street", "night drive", "city dominance"],
    energySignals: ["confident mid-to-high energy", "bass-driven", "swaggering groove"],
    allowedGenres: ["east-coast hip-hop", "west-coast hip-hop", "luxury rap", "trap", "mainstream rap"],
    forbiddenGenres: ["K-pop", "J-rock", "soft acoustic pop", "ambient"],
    referenceVibes: [
      "Nas - N.Y. State of Mind",
      "JAY-Z - U Don't Know",
      "a black car gliding past a glowing skyline",
    ],
    titleExamples: ["Skyline Flex", "Downtown Black Car"],
    avoidWhen: [
      "the scene is a quiet rainy room",
      "the mood calls for soft acoustic pop",
      "the setting is a bright K-pop moment",
    ],
  },
  {
    id: "highteen-pop-room",
    name: "Highteen Pop Room",
    description: "Bedroom pop and teen-pop energy for highschool bedrooms, selfies, and youthful drama.",
    sceneSignals: ["bedroom", "selfie", "school hallway", "teenage room", "posters"],
    energySignals: ["playful mid-to-high tempo", "bright and dramatic", "youthful bounce"],
    allowedGenres: ["bedroom pop", "teen pop", "pop rock", "indie pop"],
    forbiddenGenres: ["dark trap", "post-rock", "noir jazz"],
    referenceVibes: [
      "Olivia Rodrigo - good 4 u",
      "Conan Gray - Maniac",
      "a teenage bedroom full of posters and fairy lights",
    ],
    titleExamples: ["Locker Room Drama", "Pink Room Diaries"],
    avoidWhen: [
      "the scene is a moody adult night",
      "the mood calls for dark or heavy hip-hop",
      "the setting is a formal or mature scene",
    ],
  },
  {
    id: "modern-romance-pop",
    name: "Modern Romance Pop",
    description: "Glowing synth-pop and modern romance for night drives, date nights, and bittersweet young love.",
    sceneSignals: ["date night", "city lights", "night drive", "rainy street", "phone light"],
    energySignals: ["mid-tempo", "glowing and emotional", "romantic pulse"],
    allowedGenres: ["synth-pop", "modern pop", "indie pop", "electro-soul"],
    forbiddenGenres: ["heavy trap", "post-rock", "classic jazz"],
    referenceVibes: [
      "LANY - ILYSB",
      "The 1975 - Robbers",
      "city lights blurring past a car window at night",
    ],
    titleExamples: ["City Lights Romance", "Night Drive Confession"],
    avoidWhen: [
      "the scene is a chaotic party",
      "the mood calls for aggressive hip-hop",
      "the setting is a bright daytime beach",
    ],
  },
  {
    id: "trendy-pop-chic",
    name: "Trendy Pop Chic",
    description: "Glossy, confident K-pop and modern pop for fashion-forward, stylish city moments.",
    sceneSignals: ["fashion", "mirror selfie", "city street", "night out", "magazine-style portrait"],
    energySignals: ["confident mid-to-high tempo", "sleek and polished", "trend-driven energy"],
    allowedGenres: ["K-pop", "trendy pop", "fashion pop", "hyper-pop"],
    forbiddenGenres: ["lo-fi", "post-rock", "old jazz"],
    referenceVibes: [
      "NewJeans - Super Shy",
      "LE SSERAFIM - Perfect Night",
      "a mirror selfie in a stylish outfit on a city street",
    ],
    titleExamples: ["Mirror Selfie Chic", "Neon Runway Pop"],
    avoidWhen: [
      "the scene is a quiet solitary room",
      "the mood calls for ambient or ballad energy",
      "the setting is a rainy melancholic day",
    ],
  },
  {
    id: "cozy-cafe-mellow",
    name: "Cozy Cafe Mellow",
    description: "Warm, gentle soul-pop and soft R&B for sunlit cafe windows and easygoing daytime moments.",
    sceneSignals: ["cafe window seat", "morning light", "bakery", "quiet table", "daylight"],
    energySignals: ["gentle low-to-mid tempo", "warm and easygoing", "soft daytime calm"],
    allowedGenres: ["jazz pop", "soul pop", "mellow R&B", "k-indie cafe pop"],
    forbiddenGenres: ["dark trap", "synthwave", "hard rock"],
    referenceVibes: [
      "Norah Jones - Don't Know Why",
      "Corinne Bailey Rae - Put Your Records On",
      "warm sunlight falling across a cafe table",
    ],
    titleExamples: ["Window Seat Mornings", "Sunlit Cafe Hours"],
    avoidWhen: [
      "the scene is a dark night street",
      "the mood calls for aggressive or heavy energy",
      "the setting is a neon nightclub",
    ],
  },
  {
    id: "hip-hop-night-drive",
    name: "Hip-Hop Night Drive",
    description: "Smooth, melodic Korean hip-hop and R&B-rap for neon night drives and late-night city cruising.",
    sceneSignals: ["night drive", "car interior", "city lights", "neon downtown", "late-night street"],
    energySignals: ["smooth mid-tempo", "melodic but rhythmic", "late-night cruise energy"],
    allowedGenres: ["K-hip-hop", "melodic rap", "alt R&B-rap", "chill trap"],
    forbiddenGenres: ["bright idol pop", "acoustic folk", "classic jazz"],
    referenceVibes: [
      "DPR LIVE - Jasmine",
      "Beenzino - If I Die Tomorrow",
      "neon city lights streaming past a car window at night",
    ],
    titleExamples: ["Neon Cruise Rap", "Late Night City Flow"],
    avoidWhen: [
      "the scene is a bright daytime scene",
      "the mood calls for acoustic or folk energy",
      "the setting is a sunny beach",
    ],
  },
  {
    id: "dark-heavy-hiphop",
    name: "Dark Heavy Hip-Hop",
    description: "Aggressive, bass-heavy trap and drill for dark, tense, high-stakes night scenes.",
    sceneSignals: ["dark street", "shadow", "black room", "underground", "night party"],
    energySignals: ["heavy and tense", "aggressive mid-to-high tempo", "bass-driven intensity"],
    allowedGenres: ["trap", "drill", "dark hip-hop", "rage rap"],
    forbiddenGenres: ["acoustic folk", "soft cafe pop", "bright K-pop"],
    referenceVibes: [
      "Travis Scott - goosebumps",
      "Pop Smoke - Dior",
      "a black room lit only by a phone screen and shadow",
    ],
    titleExamples: ["Shadow City Trap", "Underground Pressure"],
    avoidWhen: [
      "the scene is bright and cheerful",
      "the mood calls for soft acoustic or cafe pop",
      "the setting is a sunny beach day",
    ],
  },
];

const LANE_NAME_BY_ID = new Map(CURATION_LANES.map((lane) => [lane.id, lane.name]));

// GPT가 선택한 primary_lane_id로 lane name을 조회 — DB에 사람이 읽을 수 있는 이름도 함께 저장하기 위함.
export function getCurationLaneName(laneId: string): string | null {
  return LANE_NAME_BY_ID.get(laneId) ?? null;
}
